AllCops:
  TargetRubyVersion: "2.6"
  Exclude:
    - "benchmark/**/*"
    - "tmp/**/*"
StringLiterals:
  Enabled: false
  SupportedStyles:
    - single_quotes
    - double_quotes
LineLength:
  Enabled: true
  Max: 100
Style/AccessModifierDeclarations:
  Enabled: false
